name: Enchantments
main: enchantments\EnchantmentsLoader
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13]
version: 1.0.0
author: TheCheloveck
website: github.com/TheCheloveck